import React, { useState, useMemo, useRef, useEffect } from 'react';

// Comprehensive emoji data with searchable keywords
const EMOJI_DATA: Array<{ emoji: string; keywords: string[]; category: string }> = [
  // Smileys & Emotion
  { emoji: '😀', keywords: ['grin', 'happy', 'smile', 'face'], category: 'Smileys' },
  { emoji: '😃', keywords: ['happy', 'smile', 'joy', 'face'], category: 'Smileys' },
  { emoji: '😄', keywords: ['happy', 'smile', 'laugh', 'face'], category: 'Smileys' },
  { emoji: '😁', keywords: ['grin', 'happy', 'teeth', 'face'], category: 'Smileys' },
  { emoji: '😅', keywords: ['sweat', 'nervous', 'laugh', 'relief'], category: 'Smileys' },
  { emoji: '😂', keywords: ['laugh', 'cry', 'joy', 'tears', 'lol'], category: 'Smileys' },
  { emoji: '🤣', keywords: ['laugh', 'rolling', 'lol', 'rofl'], category: 'Smileys' },
  { emoji: '😊', keywords: ['blush', 'smile', 'happy', 'shy'], category: 'Smileys' },
  { emoji: '😇', keywords: ['angel', 'innocent', 'halo', 'saint'], category: 'Smileys' },
  { emoji: '🙂', keywords: ['smile', 'slight', 'face'], category: 'Smileys' },
  { emoji: '😉', keywords: ['wink', 'flirt', 'face'], category: 'Smileys' },
  { emoji: '😌', keywords: ['relieved', 'calm', 'peaceful'], category: 'Smileys' },
  { emoji: '😍', keywords: ['love', 'heart', 'eyes', 'crush'], category: 'Smileys' },
  { emoji: '🥰', keywords: ['love', 'hearts', 'adore', 'affection'], category: 'Smileys' },
  { emoji: '😘', keywords: ['kiss', 'love', 'heart', 'blow'], category: 'Smileys' },
  { emoji: '😎', keywords: ['cool', 'sunglasses', 'awesome'], category: 'Smileys' },
  { emoji: '🤓', keywords: ['nerd', 'geek', 'glasses', 'smart'], category: 'Smileys' },
  { emoji: '🧐', keywords: ['monocle', 'thinking', 'curious', 'inspect'], category: 'Smileys' },
  { emoji: '🤔', keywords: ['think', 'hmm', 'wonder', 'ponder'], category: 'Smileys' },
  { emoji: '🤨', keywords: ['raised', 'eyebrow', 'skeptic', 'suspicious'], category: 'Smileys' },
  { emoji: '😐', keywords: ['neutral', 'meh', 'blank', 'straight'], category: 'Smileys' },
  { emoji: '😑', keywords: ['expressionless', 'annoyed', 'unamused'], category: 'Smileys' },
  { emoji: '😶', keywords: ['silent', 'mute', 'speechless', 'quiet'], category: 'Smileys' },
  { emoji: '🙄', keywords: ['eyeroll', 'annoyed', 'whatever', 'bored'], category: 'Smileys' },
  { emoji: '😏', keywords: ['smirk', 'smug', 'sly', 'flirt'], category: 'Smileys' },
  { emoji: '😣', keywords: ['persevere', 'struggle', 'frustrated'], category: 'Smileys' },
  { emoji: '😥', keywords: ['sad', 'disappointed', 'relieved'], category: 'Smileys' },
  { emoji: '😮', keywords: ['surprised', 'wow', 'shock', 'gasp'], category: 'Smileys' },
  { emoji: '🤯', keywords: ['mind', 'blown', 'exploding', 'shock'], category: 'Smileys' },
  { emoji: '😱', keywords: ['scream', 'fear', 'scared', 'horror'], category: 'Smileys' },
  { emoji: '😴', keywords: ['sleep', 'tired', 'zzz', 'snore'], category: 'Smileys' },
  { emoji: '🤤', keywords: ['drool', 'hungry', 'yummy', 'want'], category: 'Smileys' },
  { emoji: '😷', keywords: ['mask', 'sick', 'ill', 'covid'], category: 'Smileys' },
  { emoji: '🤒', keywords: ['sick', 'fever', 'thermometer', 'ill'], category: 'Smileys' },
  { emoji: '🤢', keywords: ['nauseous', 'sick', 'green', 'ill'], category: 'Smileys' },
  { emoji: '🤮', keywords: ['vomit', 'sick', 'puke', 'gross'], category: 'Smileys' },
  { emoji: '😈', keywords: ['devil', 'evil', 'smiling', 'mischief', 'horns'], category: 'Smileys' },
  { emoji: '👿', keywords: ['devil', 'angry', 'evil', 'imp'], category: 'Smileys' },
  { emoji: '💀', keywords: ['skull', 'death', 'dead', 'skeleton'], category: 'Smileys' },
  { emoji: '☠️', keywords: ['skull', 'crossbones', 'death', 'pirate', 'danger'], category: 'Smileys' },
  { emoji: '👻', keywords: ['ghost', 'spirit', 'spooky', 'halloween'], category: 'Smileys' },
  { emoji: '👽', keywords: ['alien', 'ufo', 'extraterrestrial', 'space'], category: 'Smileys' },
  { emoji: '🤖', keywords: ['robot', 'bot', 'ai', 'android', 'machine'], category: 'Smileys' },
  { emoji: '💩', keywords: ['poop', 'poo', 'shit', 'crap'], category: 'Smileys' },
  { emoji: '🎃', keywords: ['pumpkin', 'halloween', 'jack', 'lantern'], category: 'Smileys' },

  // People & Roles
  { emoji: '👑', keywords: ['crown', 'king', 'queen', 'royal', 'boss', 'leader'], category: 'People' },
  { emoji: '🎖️', keywords: ['medal', 'military', 'honor', 'badge', 'award'], category: 'People' },
  { emoji: '🦸', keywords: ['hero', 'superhero', 'super', 'power'], category: 'People' },
  { emoji: '🦸‍♂️', keywords: ['hero', 'superhero', 'man', 'male'], category: 'People' },
  { emoji: '🦸‍♀️', keywords: ['hero', 'superhero', 'woman', 'female'], category: 'People' },
  { emoji: '🦹', keywords: ['villain', 'super', 'evil', 'hero'], category: 'People' },
  { emoji: '🧙', keywords: ['wizard', 'mage', 'magic', 'sorcerer'], category: 'People' },
  { emoji: '🧙‍♂️', keywords: ['wizard', 'mage', 'magic', 'man'], category: 'People' },
  { emoji: '🧙‍♀️', keywords: ['witch', 'mage', 'magic', 'woman'], category: 'People' },
  { emoji: '🥷', keywords: ['ninja', 'stealth', 'silent', 'assassin'], category: 'People' },
  { emoji: '👨‍💻', keywords: ['developer', 'programmer', 'coder', 'tech', 'man'], category: 'People' },
  { emoji: '👩‍💻', keywords: ['developer', 'programmer', 'coder', 'tech', 'woman'], category: 'People' },
  { emoji: '🧑‍💻', keywords: ['developer', 'programmer', 'coder', 'tech'], category: 'People' },
  { emoji: '👨‍🔬', keywords: ['scientist', 'research', 'lab', 'man'], category: 'People' },
  { emoji: '👩‍🔬', keywords: ['scientist', 'research', 'lab', 'woman'], category: 'People' },
  { emoji: '👨‍🚀', keywords: ['astronaut', 'space', 'rocket', 'man'], category: 'People' },
  { emoji: '👩‍🚀', keywords: ['astronaut', 'space', 'rocket', 'woman'], category: 'People' },
  { emoji: '👨‍🎨', keywords: ['artist', 'painter', 'creative', 'man'], category: 'People' },
  { emoji: '👩‍🎨', keywords: ['artist', 'painter', 'creative', 'woman'], category: 'People' },
  { emoji: '👨‍🏫', keywords: ['teacher', 'professor', 'instructor', 'man'], category: 'People' },
  { emoji: '👩‍🏫', keywords: ['teacher', 'professor', 'instructor', 'woman'], category: 'People' },
  { emoji: '👨‍⚕️', keywords: ['doctor', 'health', 'medical', 'man'], category: 'People' },
  { emoji: '👩‍⚕️', keywords: ['doctor', 'health', 'medical', 'woman'], category: 'People' },
  { emoji: '👨‍🍳', keywords: ['chef', 'cook', 'kitchen', 'man'], category: 'People' },
  { emoji: '👩‍🍳', keywords: ['chef', 'cook', 'kitchen', 'woman'], category: 'People' },
  { emoji: '👨‍🔧', keywords: ['mechanic', 'repair', 'fix', 'man'], category: 'People' },
  { emoji: '👩‍🔧', keywords: ['mechanic', 'repair', 'fix', 'woman'], category: 'People' },
  { emoji: '👷', keywords: ['construction', 'worker', 'builder', 'hard', 'hat'], category: 'People' },
  { emoji: '💂', keywords: ['guard', 'soldier', 'protect', 'security'], category: 'People' },
  { emoji: '🕵️', keywords: ['detective', 'spy', 'investigate', 'search', 'sleuth'], category: 'People' },
  { emoji: '👮', keywords: ['police', 'cop', 'officer', 'law'], category: 'People' },
  { emoji: '🧝', keywords: ['elf', 'fantasy', 'magic'], category: 'People' },
  { emoji: '🧛', keywords: ['vampire', 'dracula', 'dark', 'night'], category: 'People' },
  { emoji: '🧟', keywords: ['zombie', 'undead', 'dead'], category: 'People' },
  { emoji: '🧞', keywords: ['genie', 'magic', 'wish', 'lamp'], category: 'People' },
  { emoji: '🧜', keywords: ['mermaid', 'merman', 'sea', 'ocean'], category: 'People' },
  { emoji: '🧚', keywords: ['fairy', 'magic', 'fantasy', 'wings'], category: 'People' },
  { emoji: '👼', keywords: ['angel', 'baby', 'cherub', 'innocent'], category: 'People' },
  { emoji: '🎅', keywords: ['santa', 'christmas', 'claus', 'holiday'], category: 'People' },
  { emoji: '🤴', keywords: ['prince', 'royal', 'king', 'crown'], category: 'People' },
  { emoji: '👸', keywords: ['princess', 'royal', 'queen', 'crown'], category: 'People' },
  { emoji: '🤵', keywords: ['groom', 'tuxedo', 'suit', 'formal'], category: 'People' },
  { emoji: '👰', keywords: ['bride', 'wedding', 'veil', 'marriage'], category: 'People' },
  { emoji: '🎭', keywords: ['theater', 'mask', 'drama', 'acting', 'perform'], category: 'People' },
  { emoji: '👾', keywords: ['alien', 'monster', 'game', 'invader', 'space'], category: 'People' },
  { emoji: '👤', keywords: ['person', 'user', 'silhouette', 'profile'], category: 'People' },
  { emoji: '👥', keywords: ['people', 'users', 'group', 'team', 'silhouettes'], category: 'People' },

  // Gestures & Body
  { emoji: '👋', keywords: ['wave', 'hello', 'hi', 'bye', 'hand'], category: 'Gestures' },
  { emoji: '🤚', keywords: ['hand', 'raised', 'stop', 'back'], category: 'Gestures' },
  { emoji: '✋', keywords: ['hand', 'stop', 'high', 'five'], category: 'Gestures' },
  { emoji: '🖐️', keywords: ['hand', 'fingers', 'splayed', 'five'], category: 'Gestures' },
  { emoji: '👌', keywords: ['ok', 'perfect', 'good', 'nice'], category: 'Gestures' },
  { emoji: '🤌', keywords: ['pinched', 'italian', 'hand', 'chef'], category: 'Gestures' },
  { emoji: '✌️', keywords: ['peace', 'victory', 'two', 'fingers'], category: 'Gestures' },
  { emoji: '🤞', keywords: ['crossed', 'fingers', 'luck', 'hope'], category: 'Gestures' },
  { emoji: '🤟', keywords: ['love', 'you', 'rock', 'hand'], category: 'Gestures' },
  { emoji: '🤘', keywords: ['rock', 'metal', 'horns', 'hand'], category: 'Gestures' },
  { emoji: '👍', keywords: ['thumbs', 'up', 'good', 'like', 'yes', 'approve'], category: 'Gestures' },
  { emoji: '👎', keywords: ['thumbs', 'down', 'bad', 'dislike', 'no'], category: 'Gestures' },
  { emoji: '👊', keywords: ['fist', 'punch', 'bump', 'power'], category: 'Gestures' },
  { emoji: '✊', keywords: ['fist', 'raised', 'power', 'solidarity'], category: 'Gestures' },
  { emoji: '🤛', keywords: ['fist', 'left', 'bump'], category: 'Gestures' },
  { emoji: '🤜', keywords: ['fist', 'right', 'bump'], category: 'Gestures' },
  { emoji: '👏', keywords: ['clap', 'applause', 'bravo', 'hands'], category: 'Gestures' },
  { emoji: '🙌', keywords: ['hands', 'raised', 'celebration', 'hooray'], category: 'Gestures' },
  { emoji: '🤝', keywords: ['handshake', 'deal', 'agreement', 'shake'], category: 'Gestures' },
  { emoji: '🙏', keywords: ['pray', 'please', 'thanks', 'hope', 'namaste'], category: 'Gestures' },
  { emoji: '💪', keywords: ['muscle', 'strong', 'flex', 'bicep', 'arm'], category: 'Gestures' },
  { emoji: '🦾', keywords: ['robot', 'arm', 'prosthetic', 'mechanical'], category: 'Gestures' },
  { emoji: '🖕', keywords: ['middle', 'finger', 'rude', 'angry'], category: 'Gestures' },
  { emoji: '☝️', keywords: ['point', 'up', 'finger', 'one'], category: 'Gestures' },
  { emoji: '👆', keywords: ['point', 'up', 'finger', 'backhand'], category: 'Gestures' },
  { emoji: '👇', keywords: ['point', 'down', 'finger', 'backhand'], category: 'Gestures' },
  { emoji: '👈', keywords: ['point', 'left', 'finger', 'backhand'], category: 'Gestures' },
  { emoji: '👉', keywords: ['point', 'right', 'finger', 'backhand'], category: 'Gestures' },
  { emoji: '👁️', keywords: ['eye', 'see', 'look', 'watch', 'vision'], category: 'Gestures' },
  { emoji: '👀', keywords: ['eyes', 'look', 'see', 'watch', 'stare'], category: 'Gestures' },
  { emoji: '👅', keywords: ['tongue', 'taste', 'lick'], category: 'Gestures' },
  { emoji: '👄', keywords: ['lips', 'mouth', 'kiss'], category: 'Gestures' },
  { emoji: '🧠', keywords: ['brain', 'mind', 'think', 'smart', 'intelligence'], category: 'Gestures' },
  { emoji: '🗣️', keywords: ['speak', 'talk', 'head', 'voice', 'speech'], category: 'Gestures' },

  // Hearts & Love
  { emoji: '❤️', keywords: ['red', 'heart', 'love', 'like'], category: 'Hearts' },
  { emoji: '🧡', keywords: ['orange', 'heart', 'love', 'warm'], category: 'Hearts' },
  { emoji: '💛', keywords: ['yellow', 'heart', 'love', 'friendship'], category: 'Hearts' },
  { emoji: '💚', keywords: ['green', 'heart', 'love', 'support', 'health'], category: 'Hearts' },
  { emoji: '💙', keywords: ['blue', 'heart', 'love', 'trust'], category: 'Hearts' },
  { emoji: '💜', keywords: ['purple', 'heart', 'love'], category: 'Hearts' },
  { emoji: '🖤', keywords: ['black', 'heart', 'dark', 'love'], category: 'Hearts' },
  { emoji: '🤍', keywords: ['white', 'heart', 'pure', 'love'], category: 'Hearts' },
  { emoji: '🤎', keywords: ['brown', 'heart', 'love'], category: 'Hearts' },
  { emoji: '💔', keywords: ['broken', 'heart', 'sad', 'love'], category: 'Hearts' },
  { emoji: '❤️‍🔥', keywords: ['heart', 'fire', 'passion', 'love'], category: 'Hearts' },
  { emoji: '❤️‍🩹', keywords: ['heart', 'mending', 'healing', 'love'], category: 'Hearts' },
  { emoji: '💕', keywords: ['hearts', 'two', 'love', 'couple'], category: 'Hearts' },
  { emoji: '💞', keywords: ['hearts', 'revolving', 'love'], category: 'Hearts' },
  { emoji: '💓', keywords: ['heart', 'beating', 'love', 'alive'], category: 'Hearts' },
  { emoji: '💗', keywords: ['heart', 'growing', 'love', 'pink'], category: 'Hearts' },
  { emoji: '💖', keywords: ['heart', 'sparkle', 'love', 'pink'], category: 'Hearts' },
  { emoji: '💝', keywords: ['heart', 'ribbon', 'gift', 'love', 'valentine'], category: 'Hearts' },
  { emoji: '💘', keywords: ['heart', 'arrow', 'cupid', 'love'], category: 'Hearts' },
  { emoji: '💌', keywords: ['letter', 'love', 'envelope', 'mail'], category: 'Hearts' },
  { emoji: '💋', keywords: ['kiss', 'lips', 'love', 'lipstick'], category: 'Hearts' },
  { emoji: '🫶', keywords: ['heart', 'hands', 'love', 'care'], category: 'Hearts' },

  // Animals
  { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'cute'], category: 'Animals' },
  { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'cute'], category: 'Animals' },
  { emoji: '🐭', keywords: ['mouse', 'rat', 'rodent', 'cute'], category: 'Animals' },
  { emoji: '🐹', keywords: ['hamster', 'pet', 'rodent', 'cute'], category: 'Animals' },
  { emoji: '🐰', keywords: ['rabbit', 'bunny', 'pet', 'cute'], category: 'Animals' },
  { emoji: '🦊', keywords: ['fox', 'clever', 'cunning', 'red'], category: 'Animals' },
  { emoji: '🐻', keywords: ['bear', 'grizzly', 'brown', 'strong'], category: 'Animals' },
  { emoji: '🐼', keywords: ['panda', 'bear', 'bamboo', 'cute', 'china'], category: 'Animals' },
  { emoji: '🐨', keywords: ['koala', 'australia', 'cute', 'bear'], category: 'Animals' },
  { emoji: '🐯', keywords: ['tiger', 'cat', 'stripe', 'fierce'], category: 'Animals' },
  { emoji: '🦁', keywords: ['lion', 'king', 'roar', 'cat', 'pride'], category: 'Animals' },
  { emoji: '🐮', keywords: ['cow', 'moo', 'farm', 'milk'], category: 'Animals' },
  { emoji: '🐷', keywords: ['pig', 'oink', 'farm', 'pork'], category: 'Animals' },
  { emoji: '🐸', keywords: ['frog', 'toad', 'ribbit', 'green'], category: 'Animals' },
  { emoji: '🐵', keywords: ['monkey', 'ape', 'banana', 'primate'], category: 'Animals' },
  { emoji: '🙈', keywords: ['monkey', 'see', 'no', 'evil', 'cover'], category: 'Animals' },
  { emoji: '🙉', keywords: ['monkey', 'hear', 'no', 'evil', 'cover'], category: 'Animals' },
  { emoji: '🙊', keywords: ['monkey', 'speak', 'no', 'evil', 'cover'], category: 'Animals' },
  { emoji: '🐔', keywords: ['chicken', 'hen', 'bird', 'farm'], category: 'Animals' },
  { emoji: '🐧', keywords: ['penguin', 'bird', 'ice', 'cold', 'linux'], category: 'Animals' },
  { emoji: '🐦', keywords: ['bird', 'fly', 'tweet', 'chirp'], category: 'Animals' },
  { emoji: '🐤', keywords: ['chick', 'baby', 'bird', 'chicken'], category: 'Animals' },
  { emoji: '🦆', keywords: ['duck', 'bird', 'quack', 'water'], category: 'Animals' },
  { emoji: '🦅', keywords: ['eagle', 'bird', 'fly', 'america', 'soar'], category: 'Animals' },
  { emoji: '🦉', keywords: ['owl', 'bird', 'night', 'wise', 'hoot'], category: 'Animals' },
  { emoji: '🦇', keywords: ['bat', 'vampire', 'night', 'fly'], category: 'Animals' },
  { emoji: '🐺', keywords: ['wolf', 'howl', 'wild', 'pack'], category: 'Animals' },
  { emoji: '🐗', keywords: ['boar', 'pig', 'wild', 'tusk'], category: 'Animals' },
  { emoji: '🐴', keywords: ['horse', 'pony', 'ride', 'stable'], category: 'Animals' },
  { emoji: '🦄', keywords: ['unicorn', 'horse', 'magic', 'fantasy', 'rainbow'], category: 'Animals' },
  { emoji: '🐝', keywords: ['bee', 'honey', 'buzz', 'insect', 'busy'], category: 'Animals' },
  { emoji: '🐛', keywords: ['bug', 'caterpillar', 'insect', 'debug', 'worm'], category: 'Animals' },
  { emoji: '🦋', keywords: ['butterfly', 'insect', 'transform', 'beautiful'], category: 'Animals' },
  { emoji: '🐌', keywords: ['snail', 'slow', 'shell', 'slug'], category: 'Animals' },
  { emoji: '🐞', keywords: ['ladybug', 'beetle', 'insect', 'luck'], category: 'Animals' },
  { emoji: '🐜', keywords: ['ant', 'insect', 'small', 'work', 'colony'], category: 'Animals' },
  { emoji: '🦗', keywords: ['cricket', 'grasshopper', 'insect', 'jump'], category: 'Animals' },
  { emoji: '🕷️', keywords: ['spider', 'web', 'insect', 'creepy'], category: 'Animals' },
  { emoji: '🦂', keywords: ['scorpion', 'sting', 'desert', 'danger'], category: 'Animals' },
  { emoji: '🐢', keywords: ['turtle', 'tortoise', 'slow', 'shell'], category: 'Animals' },
  { emoji: '🐍', keywords: ['snake', 'serpent', 'slither', 'python'], category: 'Animals' },
  { emoji: '🦎', keywords: ['lizard', 'reptile', 'gecko'], category: 'Animals' },
  { emoji: '🐉', keywords: ['dragon', 'fire', 'fantasy', 'chinese'], category: 'Animals' },
  { emoji: '🐲', keywords: ['dragon', 'face', 'fantasy', 'chinese'], category: 'Animals' },
  { emoji: '🦖', keywords: ['trex', 'dinosaur', 'rex', 'prehistoric'], category: 'Animals' },
  { emoji: '🦕', keywords: ['dinosaur', 'sauropod', 'prehistoric', 'long'], category: 'Animals' },
  { emoji: '🐙', keywords: ['octopus', 'sea', 'tentacle', 'squid'], category: 'Animals' },
  { emoji: '🦑', keywords: ['squid', 'sea', 'tentacle', 'calamari'], category: 'Animals' },
  { emoji: '🦐', keywords: ['shrimp', 'sea', 'prawn', 'seafood'], category: 'Animals' },
  { emoji: '🦀', keywords: ['crab', 'sea', 'pinch', 'seafood'], category: 'Animals' },
  { emoji: '🐡', keywords: ['blowfish', 'puffer', 'fish', 'sea'], category: 'Animals' },
  { emoji: '🐠', keywords: ['fish', 'tropical', 'sea', 'aquarium'], category: 'Animals' },
  { emoji: '🐟', keywords: ['fish', 'sea', 'swimming', 'aquatic'], category: 'Animals' },
  { emoji: '🐬', keywords: ['dolphin', 'sea', 'smart', 'flipper'], category: 'Animals' },
  { emoji: '🐳', keywords: ['whale', 'sea', 'spout', 'ocean'], category: 'Animals' },
  { emoji: '🦈', keywords: ['shark', 'sea', 'jaws', 'danger'], category: 'Animals' },
  { emoji: '🦭', keywords: ['seal', 'sea', 'cute', 'ocean'], category: 'Animals' },
  { emoji: '🐊', keywords: ['crocodile', 'alligator', 'reptile', 'swamp'], category: 'Animals' },
  { emoji: '🦧', keywords: ['orangutan', 'ape', 'primate', 'monkey'], category: 'Animals' },
  { emoji: '🦍', keywords: ['gorilla', 'ape', 'primate', 'strong'], category: 'Animals' },
  { emoji: '🐘', keywords: ['elephant', 'big', 'trunk', 'africa'], category: 'Animals' },
  { emoji: '🦏', keywords: ['rhino', 'rhinoceros', 'horn', 'africa'], category: 'Animals' },
  { emoji: '🦛', keywords: ['hippo', 'hippopotamus', 'water', 'africa'], category: 'Animals' },
  { emoji: '🐪', keywords: ['camel', 'desert', 'hump', 'dromedary'], category: 'Animals' },
  { emoji: '🦒', keywords: ['giraffe', 'tall', 'neck', 'spots'], category: 'Animals' },
  { emoji: '🦓', keywords: ['zebra', 'stripes', 'horse', 'africa'], category: 'Animals' },
  { emoji: '🦘', keywords: ['kangaroo', 'australia', 'jump', 'pouch'], category: 'Animals' },
  { emoji: '🦬', keywords: ['bison', 'buffalo', 'america', 'wild'], category: 'Animals' },
  { emoji: '🐃', keywords: ['buffalo', 'water', 'ox', 'farm'], category: 'Animals' },
  { emoji: '🦌', keywords: ['deer', 'stag', 'antler', 'forest'], category: 'Animals' },
  { emoji: '🦙', keywords: ['llama', 'alpaca', 'wool', 'peru'], category: 'Animals' },
  { emoji: '🦥', keywords: ['sloth', 'slow', 'lazy', 'sleep'], category: 'Animals' },
  { emoji: '🦦', keywords: ['otter', 'sea', 'cute', 'swim'], category: 'Animals' },
  { emoji: '🦨', keywords: ['skunk', 'stink', 'smell', 'stripe'], category: 'Animals' },
  { emoji: '🦡', keywords: ['badger', 'honey', 'dig', 'stripe'], category: 'Animals' },
  { emoji: '🐾', keywords: ['paw', 'prints', 'pet', 'animal', 'dog', 'cat'], category: 'Animals' },
  { emoji: '🦠', keywords: ['microbe', 'virus', 'bacteria', 'bug', 'germ'], category: 'Animals' },

  // Nature & Plants
  { emoji: '🌲', keywords: ['tree', 'evergreen', 'pine', 'forest', 'christmas'], category: 'Nature' },
  { emoji: '🌳', keywords: ['tree', 'deciduous', 'forest', 'nature'], category: 'Nature' },
  { emoji: '🌴', keywords: ['palm', 'tree', 'beach', 'tropical'], category: 'Nature' },
  { emoji: '🌵', keywords: ['cactus', 'desert', 'plant', 'prickly'], category: 'Nature' },
  { emoji: '🌱', keywords: ['seedling', 'plant', 'grow', 'sprout'], category: 'Nature' },
  { emoji: '🌿', keywords: ['herb', 'plant', 'green', 'leaf'], category: 'Nature' },
  { emoji: '☘️', keywords: ['shamrock', 'clover', 'irish', 'luck'], category: 'Nature' },
  { emoji: '🍀', keywords: ['clover', 'four', 'leaf', 'luck'], category: 'Nature' },
  { emoji: '🍁', keywords: ['maple', 'leaf', 'fall', 'autumn', 'canada'], category: 'Nature' },
  { emoji: '🍂', keywords: ['fallen', 'leaf', 'fall', 'autumn'], category: 'Nature' },
  { emoji: '🍃', keywords: ['leaf', 'fluttering', 'wind', 'blow'], category: 'Nature' },
  { emoji: '🌸', keywords: ['cherry', 'blossom', 'flower', 'spring', 'japan'], category: 'Nature' },
  { emoji: '💐', keywords: ['bouquet', 'flowers', 'gift', 'arrangement'], category: 'Nature' },
  { emoji: '🌷', keywords: ['tulip', 'flower', 'spring', 'netherlands'], category: 'Nature' },
  { emoji: '🌹', keywords: ['rose', 'flower', 'love', 'romantic'], category: 'Nature' },
  { emoji: '🥀', keywords: ['wilted', 'flower', 'dead', 'sad'], category: 'Nature' },
  { emoji: '🌺', keywords: ['hibiscus', 'flower', 'tropical', 'hawaii'], category: 'Nature' },
  { emoji: '🌻', keywords: ['sunflower', 'flower', 'sun', 'yellow'], category: 'Nature' },
  { emoji: '🌼', keywords: ['blossom', 'flower', 'yellow', 'daisy'], category: 'Nature' },

  // Weather & Sky
  { emoji: '☀️', keywords: ['sun', 'sunny', 'bright', 'day', 'light'], category: 'Weather' },
  { emoji: '🌤️', keywords: ['sun', 'cloud', 'partly', 'cloudy'], category: 'Weather' },
  { emoji: '⛅', keywords: ['sun', 'cloud', 'partly', 'cloudy'], category: 'Weather' },
  { emoji: '🌥️', keywords: ['cloud', 'sun', 'behind', 'mostly'], category: 'Weather' },
  { emoji: '☁️', keywords: ['cloud', 'cloudy', 'weather', 'sky'], category: 'Weather' },
  { emoji: '🌦️', keywords: ['rain', 'sun', 'cloud', 'shower'], category: 'Weather' },
  { emoji: '🌧️', keywords: ['rain', 'cloud', 'rainy', 'weather'], category: 'Weather' },
  { emoji: '⛈️', keywords: ['thunder', 'storm', 'rain', 'lightning'], category: 'Weather' },
  { emoji: '🌩️', keywords: ['lightning', 'cloud', 'storm', 'thunder'], category: 'Weather' },
  { emoji: '🌨️', keywords: ['snow', 'cloud', 'snowy', 'winter'], category: 'Weather' },
  { emoji: '❄️', keywords: ['snow', 'ice', 'cold', 'freeze', 'winter', 'flake'], category: 'Weather' },
  { emoji: '💨', keywords: ['wind', 'blow', 'dash', 'fast', 'air'], category: 'Weather' },
  { emoji: '🌪️', keywords: ['tornado', 'cyclone', 'twister', 'storm'], category: 'Weather' },
  { emoji: '🌫️', keywords: ['fog', 'foggy', 'mist', 'hazy'], category: 'Weather' },
  { emoji: '🌈', keywords: ['rainbow', 'color', 'pride', 'spectrum'], category: 'Weather' },
  { emoji: '⚡', keywords: ['lightning', 'electric', 'power', 'energy', 'fast', 'bolt', 'thunder'], category: 'Weather' },
  { emoji: '🔥', keywords: ['fire', 'flame', 'hot', 'burn', 'lit'], category: 'Weather' },
  { emoji: '💧', keywords: ['water', 'drop', 'liquid', 'wet'], category: 'Weather' },
  { emoji: '🌊', keywords: ['wave', 'ocean', 'sea', 'water', 'surf'], category: 'Weather' },
  { emoji: '🌙', keywords: ['moon', 'night', 'crescent', 'dark', 'sleep'], category: 'Weather' },
  { emoji: '🌛', keywords: ['moon', 'first', 'quarter', 'face'], category: 'Weather' },
  { emoji: '🌜', keywords: ['moon', 'last', 'quarter', 'face'], category: 'Weather' },
  { emoji: '🌝', keywords: ['moon', 'full', 'face', 'bright'], category: 'Weather' },
  { emoji: '🌞', keywords: ['sun', 'face', 'bright', 'happy'], category: 'Weather' },
  { emoji: '⭐', keywords: ['star', 'yellow', 'favorite', 'best'], category: 'Weather' },
  { emoji: '🌟', keywords: ['star', 'glow', 'bright', 'shiny'], category: 'Weather' },
  { emoji: '✨', keywords: ['sparkle', 'star', 'shine', 'magic', 'new'], category: 'Weather' },
  { emoji: '💫', keywords: ['dizzy', 'star', 'circle', 'shooting'], category: 'Weather' },
  { emoji: '☄️', keywords: ['comet', 'meteor', 'space', 'shooting', 'star'], category: 'Weather' },

  // Food & Drink
  { emoji: '🍎', keywords: ['apple', 'red', 'fruit', 'healthy'], category: 'Food' },
  { emoji: '🍏', keywords: ['apple', 'green', 'fruit', 'healthy'], category: 'Food' },
  { emoji: '🍐', keywords: ['pear', 'fruit', 'green'], category: 'Food' },
  { emoji: '🍊', keywords: ['orange', 'fruit', 'citrus', 'tangerine'], category: 'Food' },
  { emoji: '🍋', keywords: ['lemon', 'citrus', 'sour', 'yellow'], category: 'Food' },
  { emoji: '🍌', keywords: ['banana', 'fruit', 'yellow', 'monkey'], category: 'Food' },
  { emoji: '🍉', keywords: ['watermelon', 'fruit', 'summer', 'red'], category: 'Food' },
  { emoji: '🍇', keywords: ['grapes', 'fruit', 'wine', 'purple'], category: 'Food' },
  { emoji: '🍓', keywords: ['strawberry', 'fruit', 'berry', 'red'], category: 'Food' },
  { emoji: '🫐', keywords: ['blueberry', 'fruit', 'berry', 'blue'], category: 'Food' },
  { emoji: '🍒', keywords: ['cherry', 'cherries', 'fruit', 'red'], category: 'Food' },
  { emoji: '🍑', keywords: ['peach', 'fruit', 'butt', 'emoji'], category: 'Food' },
  { emoji: '🥭', keywords: ['mango', 'fruit', 'tropical', 'yellow'], category: 'Food' },
  { emoji: '🍍', keywords: ['pineapple', 'fruit', 'tropical'], category: 'Food' },
  { emoji: '🥥', keywords: ['coconut', 'tropical', 'brown'], category: 'Food' },
  { emoji: '🥝', keywords: ['kiwi', 'fruit', 'green'], category: 'Food' },
  { emoji: '🍅', keywords: ['tomato', 'vegetable', 'red'], category: 'Food' },
  { emoji: '🥑', keywords: ['avocado', 'green', 'guacamole'], category: 'Food' },
  { emoji: '🥕', keywords: ['carrot', 'vegetable', 'orange'], category: 'Food' },
  { emoji: '🌽', keywords: ['corn', 'maize', 'vegetable', 'yellow'], category: 'Food' },
  { emoji: '🌶️', keywords: ['pepper', 'hot', 'spicy', 'chili'], category: 'Food' },
  { emoji: '🥒', keywords: ['cucumber', 'pickle', 'vegetable'], category: 'Food' },
  { emoji: '🥬', keywords: ['lettuce', 'leafy', 'green', 'salad'], category: 'Food' },
  { emoji: '🥦', keywords: ['broccoli', 'vegetable', 'green'], category: 'Food' },
  { emoji: '🧄', keywords: ['garlic', 'spice', 'cooking'], category: 'Food' },
  { emoji: '🧅', keywords: ['onion', 'vegetable', 'cry'], category: 'Food' },
  { emoji: '🥔', keywords: ['potato', 'vegetable', 'fries'], category: 'Food' },
  { emoji: '🍞', keywords: ['bread', 'loaf', 'toast', 'carb'], category: 'Food' },
  { emoji: '🥐', keywords: ['croissant', 'bread', 'french', 'pastry'], category: 'Food' },
  { emoji: '🥖', keywords: ['baguette', 'bread', 'french'], category: 'Food' },
  { emoji: '🥨', keywords: ['pretzel', 'snack', 'twisted'], category: 'Food' },
  { emoji: '🧀', keywords: ['cheese', 'dairy', 'yellow'], category: 'Food' },
  { emoji: '🥚', keywords: ['egg', 'breakfast', 'chicken'], category: 'Food' },
  { emoji: '🍳', keywords: ['cooking', 'egg', 'frying', 'pan'], category: 'Food' },
  { emoji: '🥞', keywords: ['pancakes', 'breakfast', 'stack'], category: 'Food' },
  { emoji: '🧇', keywords: ['waffle', 'breakfast', 'belgian'], category: 'Food' },
  { emoji: '🥓', keywords: ['bacon', 'meat', 'breakfast', 'pork'], category: 'Food' },
  { emoji: '🍔', keywords: ['burger', 'hamburger', 'food', 'fast'], category: 'Food' },
  { emoji: '🍟', keywords: ['fries', 'french', 'food', 'fast'], category: 'Food' },
  { emoji: '🍕', keywords: ['pizza', 'food', 'italian', 'slice'], category: 'Food' },
  { emoji: '🌭', keywords: ['hotdog', 'food', 'fast', 'sausage'], category: 'Food' },
  { emoji: '🥪', keywords: ['sandwich', 'food', 'bread', 'lunch'], category: 'Food' },
  { emoji: '🌮', keywords: ['taco', 'mexican', 'food'], category: 'Food' },
  { emoji: '🌯', keywords: ['burrito', 'mexican', 'food', 'wrap'], category: 'Food' },
  { emoji: '🥗', keywords: ['salad', 'healthy', 'green', 'vegetable'], category: 'Food' },
  { emoji: '🍜', keywords: ['noodle', 'ramen', 'soup', 'bowl'], category: 'Food' },
  { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'italian', 'noodle'], category: 'Food' },
  { emoji: '🍣', keywords: ['sushi', 'japanese', 'fish', 'rice'], category: 'Food' },
  { emoji: '🍱', keywords: ['bento', 'box', 'japanese', 'lunch'], category: 'Food' },
  { emoji: '🍛', keywords: ['curry', 'rice', 'indian', 'food'], category: 'Food' },
  { emoji: '🍲', keywords: ['pot', 'food', 'stew', 'soup'], category: 'Food' },
  { emoji: '🥘', keywords: ['paella', 'food', 'pan', 'spanish'], category: 'Food' },
  { emoji: '🍿', keywords: ['popcorn', 'movie', 'snack', 'cinema'], category: 'Food' },
  { emoji: '🧂', keywords: ['salt', 'spice', 'seasoning'], category: 'Food' },
  { emoji: '🍦', keywords: ['ice', 'cream', 'cone', 'dessert', 'cold'], category: 'Food' },
  { emoji: '🍧', keywords: ['shaved', 'ice', 'dessert', 'cold'], category: 'Food' },
  { emoji: '🍨', keywords: ['ice', 'cream', 'dessert', 'cold'], category: 'Food' },
  { emoji: '🍩', keywords: ['donut', 'doughnut', 'dessert', 'sweet'], category: 'Food' },
  { emoji: '🍪', keywords: ['cookie', 'dessert', 'sweet', 'chocolate'], category: 'Food' },
  { emoji: '🎂', keywords: ['cake', 'birthday', 'dessert', 'celebration'], category: 'Food' },
  { emoji: '🍰', keywords: ['cake', 'slice', 'shortcake', 'dessert'], category: 'Food' },
  { emoji: '🧁', keywords: ['cupcake', 'dessert', 'sweet', 'muffin'], category: 'Food' },
  { emoji: '🥧', keywords: ['pie', 'dessert', 'apple', 'thanksgiving'], category: 'Food' },
  { emoji: '🍫', keywords: ['chocolate', 'bar', 'sweet', 'candy'], category: 'Food' },
  { emoji: '🍬', keywords: ['candy', 'sweet', 'sugar'], category: 'Food' },
  { emoji: '🍭', keywords: ['lollipop', 'candy', 'sweet'], category: 'Food' },
  { emoji: '☕', keywords: ['coffee', 'hot', 'drink', 'cafe', 'java'], category: 'Food' },
  { emoji: '🍵', keywords: ['tea', 'hot', 'drink', 'green'], category: 'Food' },
  { emoji: '🥤', keywords: ['cup', 'straw', 'drink', 'soda'], category: 'Food' },
  { emoji: '🧃', keywords: ['juice', 'box', 'drink', 'kid'], category: 'Food' },
  { emoji: '🧊', keywords: ['ice', 'cube', 'cold', 'freeze'], category: 'Food' },
  { emoji: '🍺', keywords: ['beer', 'mug', 'drink', 'alcohol'], category: 'Food' },
  { emoji: '🍻', keywords: ['beer', 'cheers', 'drink', 'alcohol', 'mugs'], category: 'Food' },
  { emoji: '🥂', keywords: ['champagne', 'cheers', 'celebration', 'wine'], category: 'Food' },
  { emoji: '🍷', keywords: ['wine', 'glass', 'drink', 'alcohol', 'red'], category: 'Food' },
  { emoji: '🥃', keywords: ['whiskey', 'glass', 'drink', 'alcohol', 'tumbler'], category: 'Food' },
  { emoji: '🍸', keywords: ['cocktail', 'drink', 'martini', 'alcohol'], category: 'Food' },
  { emoji: '🍹', keywords: ['tropical', 'drink', 'cocktail', 'alcohol'], category: 'Food' },

  // Tools & Objects
  { emoji: '🔍', keywords: ['search', 'magnify', 'find', 'look', 'scout', 'explore', 'investigate'], category: 'Tools' },
  { emoji: '🔎', keywords: ['search', 'magnify', 'find', 'look', 'right'], category: 'Tools' },
  { emoji: '🔨', keywords: ['hammer', 'build', 'tool', 'construct', 'builder'], category: 'Tools' },
  { emoji: '🪓', keywords: ['axe', 'chop', 'wood', 'lumberjack'], category: 'Tools' },
  { emoji: '⛏️', keywords: ['pick', 'mining', 'dig', 'tool'], category: 'Tools' },
  { emoji: '⚒️', keywords: ['hammer', 'pick', 'mining', 'build'], category: 'Tools' },
  { emoji: '🛠️', keywords: ['tools', 'build', 'repair', 'fix', 'hammer', 'wrench'], category: 'Tools' },
  { emoji: '🔧', keywords: ['wrench', 'fix', 'repair', 'tool', 'mechanic'], category: 'Tools' },
  { emoji: '🪛', keywords: ['screwdriver', 'tool', 'fix', 'repair'], category: 'Tools' },
  { emoji: '🔩', keywords: ['bolt', 'nut', 'screw', 'hardware'], category: 'Tools' },
  { emoji: '⚙️', keywords: ['gear', 'settings', 'config', 'cog', 'machine'], category: 'Tools' },
  { emoji: '🗜️', keywords: ['clamp', 'compress', 'tool', 'vise'], category: 'Tools' },
  { emoji: '⚖️', keywords: ['scale', 'balance', 'justice', 'law', 'weigh'], category: 'Tools' },
  { emoji: '🔗', keywords: ['link', 'chain', 'connect', 'url'], category: 'Tools' },
  { emoji: '⛓️', keywords: ['chain', 'link', 'connect', 'locked'], category: 'Tools' },
  { emoji: '🧰', keywords: ['toolbox', 'tools', 'repair', 'box'], category: 'Tools' },
  { emoji: '🧲', keywords: ['magnet', 'attract', 'magnetic'], category: 'Tools' },
  { emoji: '⚔️', keywords: ['sword', 'battle', 'fight', 'warrior', 'combat', 'crossed'], category: 'Tools' },
  { emoji: '🗡️', keywords: ['dagger', 'knife', 'sword', 'blade', 'weapon'], category: 'Tools' },
  { emoji: '🛡️', keywords: ['shield', 'protect', 'defense', 'guard', 'security'], category: 'Tools' },
  { emoji: '🏹', keywords: ['bow', 'arrow', 'archer', 'hunt'], category: 'Tools' },
  { emoji: '🔪', keywords: ['knife', 'cut', 'blade', 'kitchen'], category: 'Tools' },
  { emoji: '💣', keywords: ['bomb', 'explode', 'danger', 'boom'], category: 'Tools' },
  { emoji: '🧨', keywords: ['dynamite', 'explosive', 'firecracker', 'boom'], category: 'Tools' },
  { emoji: '🪃', keywords: ['boomerang', 'throw', 'return', 'australia'], category: 'Tools' },
  { emoji: '🔫', keywords: ['gun', 'pistol', 'water', 'toy'], category: 'Tools' },
  { emoji: '✂️', keywords: ['scissors', 'cut', 'trim', 'snip'], category: 'Tools' },
  { emoji: '📌', keywords: ['pin', 'push', 'tack', 'mark', 'location'], category: 'Tools' },
  { emoji: '📍', keywords: ['pin', 'location', 'map', 'place'], category: 'Tools' },
  { emoji: '📎', keywords: ['paperclip', 'clip', 'attach', 'office'], category: 'Tools' },
  { emoji: '🖊️', keywords: ['pen', 'write', 'ink', 'sign'], category: 'Tools' },
  { emoji: '✏️', keywords: ['pencil', 'write', 'draw', 'edit'], category: 'Tools' },
  { emoji: '✒️', keywords: ['pen', 'nib', 'write', 'black'], category: 'Tools' },
  { emoji: '🖍️', keywords: ['crayon', 'draw', 'color', 'art'], category: 'Tools' },
  { emoji: '📝', keywords: ['memo', 'note', 'write', 'document', 'edit'], category: 'Tools' },
  { emoji: '📋', keywords: ['clipboard', 'list', 'task', 'checklist'], category: 'Tools' },
  { emoji: '🔐', keywords: ['lock', 'key', 'secure', 'closed'], category: 'Tools' },
  { emoji: '🔒', keywords: ['lock', 'closed', 'secure', 'padlock'], category: 'Tools' },
  { emoji: '🔓', keywords: ['unlock', 'open', 'padlock'], category: 'Tools' },
  { emoji: '🔑', keywords: ['key', 'lock', 'password', 'access'], category: 'Tools' },
  { emoji: '🗝️', keywords: ['key', 'old', 'vintage', 'lock'], category: 'Tools' },

  // Tech & Science
  { emoji: '💻', keywords: ['laptop', 'computer', 'pc', 'mac', 'code', 'work'], category: 'Tech' },
  { emoji: '🖥️', keywords: ['desktop', 'computer', 'monitor', 'screen', 'pc'], category: 'Tech' },
  { emoji: '🖨️', keywords: ['printer', 'print', 'paper', 'office'], category: 'Tech' },
  { emoji: '⌨️', keywords: ['keyboard', 'type', 'input', 'computer'], category: 'Tech' },
  { emoji: '🖱️', keywords: ['mouse', 'click', 'computer', 'cursor'], category: 'Tech' },
  { emoji: '🖲️', keywords: ['trackball', 'mouse', 'computer', 'input'], category: 'Tech' },
  { emoji: '💽', keywords: ['disk', 'minidisk', 'computer', 'storage'], category: 'Tech' },
  { emoji: '💾', keywords: ['floppy', 'disk', 'save', 'storage', 'data'], category: 'Tech' },
  { emoji: '💿', keywords: ['cd', 'disk', 'music', 'data'], category: 'Tech' },
  { emoji: '📀', keywords: ['dvd', 'disk', 'movie', 'data'], category: 'Tech' },
  { emoji: '📱', keywords: ['phone', 'mobile', 'smartphone', 'cell', 'iphone'], category: 'Tech' },
  { emoji: '📲', keywords: ['phone', 'call', 'incoming', 'mobile'], category: 'Tech' },
  { emoji: '☎️', keywords: ['phone', 'telephone', 'call', 'old'], category: 'Tech' },
  { emoji: '📞', keywords: ['phone', 'receiver', 'call', 'talk'], category: 'Tech' },
  { emoji: '📟', keywords: ['pager', 'beeper', 'old', 'retro'], category: 'Tech' },
  { emoji: '📠', keywords: ['fax', 'machine', 'office', 'old'], category: 'Tech' },
  { emoji: '🔋', keywords: ['battery', 'power', 'charge', 'energy'], category: 'Tech' },
  { emoji: '🔌', keywords: ['plug', 'electric', 'power', 'connect'], category: 'Tech' },
  { emoji: '💡', keywords: ['bulb', 'light', 'idea', 'bright', 'lamp'], category: 'Tech' },
  { emoji: '🔦', keywords: ['flashlight', 'light', 'torch', 'bright'], category: 'Tech' },
  { emoji: '🕯️', keywords: ['candle', 'light', 'flame', 'wax'], category: 'Tech' },
  { emoji: '📡', keywords: ['satellite', 'antenna', 'signal', 'dish'], category: 'Tech' },
  { emoji: '🛰️', keywords: ['satellite', 'space', 'orbit', 'signal'], category: 'Tech' },
  { emoji: '🧭', keywords: ['compass', 'navigate', 'direction', 'north'], category: 'Tech' },
  { emoji: '🗺️', keywords: ['map', 'world', 'travel', 'navigate', 'explore'], category: 'Tech' },
  { emoji: '🧪', keywords: ['test', 'tube', 'science', 'lab', 'experiment', 'chemistry'], category: 'Tech' },
  { emoji: '🔬', keywords: ['microscope', 'science', 'lab', 'research', 'biology'], category: 'Tech' },
  { emoji: '🔭', keywords: ['telescope', 'space', 'astronomy', 'star', 'observe'], category: 'Tech' },
  { emoji: '📐', keywords: ['ruler', 'triangle', 'architect', 'design', 'measure', 'math'], category: 'Tech' },
  { emoji: '📏', keywords: ['ruler', 'measure', 'straight', 'length'], category: 'Tech' },
  { emoji: '🧬', keywords: ['dna', 'gene', 'biology', 'science', 'helix'], category: 'Tech' },
  { emoji: '💉', keywords: ['syringe', 'needle', 'medicine', 'vaccine', 'inject'], category: 'Tech' },
  { emoji: '💊', keywords: ['pill', 'medicine', 'drug', 'pharmacy', 'health'], category: 'Tech' },
  { emoji: '🩹', keywords: ['bandage', 'heal', 'fix', 'patch', 'medical'], category: 'Tech' },
  { emoji: '🩺', keywords: ['stethoscope', 'doctor', 'medical', 'health'], category: 'Tech' },
  { emoji: '⚗️', keywords: ['alembic', 'chemistry', 'science', 'distill'], category: 'Tech' },

  // Transport
  { emoji: '🚗', keywords: ['car', 'auto', 'vehicle', 'drive'], category: 'Transport' },
  { emoji: '🚕', keywords: ['taxi', 'cab', 'car', 'ride'], category: 'Transport' },
  { emoji: '🚙', keywords: ['suv', 'car', 'vehicle', 'sport'], category: 'Transport' },
  { emoji: '🚌', keywords: ['bus', 'vehicle', 'public', 'transit'], category: 'Transport' },
  { emoji: '🚎', keywords: ['trolley', 'bus', 'electric', 'transit'], category: 'Transport' },
  { emoji: '🏎️', keywords: ['racing', 'car', 'fast', 'formula'], category: 'Transport' },
  { emoji: '🚓', keywords: ['police', 'car', 'cop', 'patrol'], category: 'Transport' },
  { emoji: '🚑', keywords: ['ambulance', 'emergency', 'medical', 'hospital'], category: 'Transport' },
  { emoji: '🚒', keywords: ['fire', 'truck', 'engine', 'emergency'], category: 'Transport' },
  { emoji: '🚐', keywords: ['minibus', 'van', 'vehicle', 'transit'], category: 'Transport' },
  { emoji: '🛻', keywords: ['pickup', 'truck', 'vehicle'], category: 'Transport' },
  { emoji: '🚚', keywords: ['truck', 'delivery', 'vehicle', 'moving'], category: 'Transport' },
  { emoji: '🚛', keywords: ['truck', 'semi', 'trailer', 'haul'], category: 'Transport' },
  { emoji: '🚜', keywords: ['tractor', 'farm', 'vehicle', 'agriculture'], category: 'Transport' },
  { emoji: '🏍️', keywords: ['motorcycle', 'racing', 'bike', 'sport'], category: 'Transport' },
  { emoji: '🛵', keywords: ['scooter', 'motor', 'vespa', 'moped'], category: 'Transport' },
  { emoji: '🚲', keywords: ['bicycle', 'bike', 'cycle', 'pedal'], category: 'Transport' },
  { emoji: '🛴', keywords: ['scooter', 'kick', 'ride'], category: 'Transport' },
  { emoji: '🚂', keywords: ['train', 'locomotive', 'steam', 'rail'], category: 'Transport' },
  { emoji: '🚃', keywords: ['train', 'railway', 'car', 'wagon'], category: 'Transport' },
  { emoji: '🚄', keywords: ['train', 'high', 'speed', 'bullet', 'shinkansen'], category: 'Transport' },
  { emoji: '🚅', keywords: ['train', 'bullet', 'high', 'speed'], category: 'Transport' },
  { emoji: '🚆', keywords: ['train', 'railway', 'transit'], category: 'Transport' },
  { emoji: '🚇', keywords: ['metro', 'subway', 'underground', 'train'], category: 'Transport' },
  { emoji: '🚈', keywords: ['train', 'light', 'rail', 'transit'], category: 'Transport' },
  { emoji: '✈️', keywords: ['airplane', 'plane', 'fly', 'travel', 'flight'], category: 'Transport' },
  { emoji: '🛫', keywords: ['airplane', 'departure', 'takeoff', 'fly'], category: 'Transport' },
  { emoji: '🛬', keywords: ['airplane', 'arrival', 'landing', 'fly'], category: 'Transport' },
  { emoji: '🛩️', keywords: ['plane', 'small', 'airplane', 'fly'], category: 'Transport' },
  { emoji: '🚁', keywords: ['helicopter', 'chopper', 'fly', 'hover'], category: 'Transport' },
  { emoji: '🛸', keywords: ['ufo', 'alien', 'spaceship', 'flying', 'saucer'], category: 'Transport' },
  { emoji: '🚀', keywords: ['rocket', 'launch', 'space', 'fast', 'ship', 'startup'], category: 'Transport' },
  { emoji: '🛶', keywords: ['canoe', 'boat', 'paddle', 'kayak'], category: 'Transport' },
  { emoji: '⛵', keywords: ['sailboat', 'boat', 'sail', 'wind'], category: 'Transport' },
  { emoji: '🚤', keywords: ['speedboat', 'boat', 'fast', 'water'], category: 'Transport' },
  { emoji: '🛥️', keywords: ['motorboat', 'boat', 'yacht'], category: 'Transport' },
  { emoji: '🛳️', keywords: ['ship', 'cruise', 'passenger', 'boat'], category: 'Transport' },
  { emoji: '⛴️', keywords: ['ferry', 'boat', 'ship', 'transport'], category: 'Transport' },
  { emoji: '🚢', keywords: ['ship', 'boat', 'cruise', 'ocean'], category: 'Transport' },
  { emoji: '⚓', keywords: ['anchor', 'ship', 'boat', 'dock'], category: 'Transport' },
  { emoji: '🚧', keywords: ['construction', 'barrier', 'road', 'block'], category: 'Transport' },
  { emoji: '🚦', keywords: ['traffic', 'light', 'signal', 'stop', 'go'], category: 'Transport' },
  { emoji: '🚥', keywords: ['traffic', 'light', 'horizontal', 'signal'], category: 'Transport' },
  { emoji: '🗼', keywords: ['tower', 'tokyo', 'japan', 'landmark'], category: 'Transport' },
  { emoji: '🗽', keywords: ['statue', 'liberty', 'usa', 'new', 'york'], category: 'Transport' },
  { emoji: '🗿', keywords: ['moai', 'statue', 'easter', 'island'], category: 'Transport' },

  // Objects & Symbols
  { emoji: '📦', keywords: ['box', 'package', 'delivery', 'ship', 'container'], category: 'Objects' },
  { emoji: '🎁', keywords: ['gift', 'present', 'wrap', 'birthday'], category: 'Objects' },
  { emoji: '💎', keywords: ['diamond', 'gem', 'jewel', 'precious', 'crystal'], category: 'Objects' },
  { emoji: '🔮', keywords: ['crystal', 'ball', 'magic', 'fortune', 'predict'], category: 'Objects' },
  { emoji: '🏆', keywords: ['trophy', 'win', 'champion', 'prize', 'gold', 'first'], category: 'Objects' },
  { emoji: '🥇', keywords: ['gold', 'medal', 'first', 'winner', 'best'], category: 'Objects' },
  { emoji: '🥈', keywords: ['silver', 'medal', 'second', 'winner'], category: 'Objects' },
  { emoji: '🥉', keywords: ['bronze', 'medal', 'third', 'winner'], category: 'Objects' },
  { emoji: '🏅', keywords: ['medal', 'sports', 'award', 'winner'], category: 'Objects' },
  { emoji: '🎖️', keywords: ['medal', 'military', 'honor', 'badge'], category: 'Objects' },
  { emoji: '🎯', keywords: ['target', 'bullseye', 'aim', 'goal', 'dart'], category: 'Objects' },
  { emoji: '🎰', keywords: ['slot', 'machine', 'casino', 'gamble', 'lucky'], category: 'Objects' },
  { emoji: '🎲', keywords: ['dice', 'game', 'roll', 'random', 'chance'], category: 'Objects' },
  { emoji: '🎮', keywords: ['game', 'controller', 'video', 'play', 'console'], category: 'Objects' },
  { emoji: '🕹️', keywords: ['joystick', 'game', 'arcade', 'control'], category: 'Objects' },
  { emoji: '🎨', keywords: ['art', 'palette', 'paint', 'color', 'creative'], category: 'Objects' },
  { emoji: '🖼️', keywords: ['picture', 'frame', 'art', 'painting'], category: 'Objects' },
  { emoji: '🎬', keywords: ['clapper', 'movie', 'film', 'action', 'cinema'], category: 'Objects' },
  { emoji: '📷', keywords: ['camera', 'photo', 'picture', 'photograph'], category: 'Objects' },
  { emoji: '📸', keywords: ['camera', 'flash', 'photo', 'selfie'], category: 'Objects' },
  { emoji: '📹', keywords: ['video', 'camera', 'record', 'film'], category: 'Objects' },
  { emoji: '🎥', keywords: ['movie', 'camera', 'film', 'cinema'], category: 'Objects' },
  { emoji: '📺', keywords: ['tv', 'television', 'screen', 'watch'], category: 'Objects' },
  { emoji: '📻', keywords: ['radio', 'music', 'broadcast', 'listen'], category: 'Objects' },
  { emoji: '🎤', keywords: ['microphone', 'mic', 'sing', 'karaoke', 'voice'], category: 'Objects' },
  { emoji: '🎧', keywords: ['headphones', 'music', 'listen', 'audio'], category: 'Objects' },
  { emoji: '🎵', keywords: ['music', 'note', 'song', 'melody'], category: 'Objects' },
  { emoji: '🎶', keywords: ['music', 'notes', 'song', 'melody'], category: 'Objects' },
  { emoji: '🎹', keywords: ['piano', 'keys', 'music', 'instrument'], category: 'Objects' },
  { emoji: '🎸', keywords: ['guitar', 'music', 'rock', 'instrument'], category: 'Objects' },
  { emoji: '🎺', keywords: ['trumpet', 'music', 'brass', 'instrument'], category: 'Objects' },
  { emoji: '🥁', keywords: ['drum', 'music', 'beat', 'percussion'], category: 'Objects' },
  { emoji: '🎻', keywords: ['violin', 'music', 'string', 'instrument'], category: 'Objects' },
  { emoji: '📚', keywords: ['books', 'library', 'read', 'study'], category: 'Objects' },
  { emoji: '📖', keywords: ['book', 'open', 'read', 'study'], category: 'Objects' },
  { emoji: '📕', keywords: ['book', 'closed', 'red', 'read'], category: 'Objects' },
  { emoji: '📗', keywords: ['book', 'green', 'read'], category: 'Objects' },
  { emoji: '📘', keywords: ['book', 'blue', 'read'], category: 'Objects' },
  { emoji: '📙', keywords: ['book', 'orange', 'read'], category: 'Objects' },
  { emoji: '📓', keywords: ['notebook', 'write', 'journal'], category: 'Objects' },
  { emoji: '📒', keywords: ['ledger', 'notebook', 'write'], category: 'Objects' },
  { emoji: '📃', keywords: ['page', 'document', 'curl', 'paper'], category: 'Objects' },
  { emoji: '📄', keywords: ['document', 'page', 'paper', 'file'], category: 'Objects' },
  { emoji: '📰', keywords: ['newspaper', 'news', 'press', 'paper'], category: 'Objects' },
  { emoji: '🗞️', keywords: ['newspaper', 'rolled', 'news', 'paper'], category: 'Objects' },
  { emoji: '📑', keywords: ['bookmark', 'tabs', 'page', 'marker'], category: 'Objects' },
  { emoji: '🔖', keywords: ['bookmark', 'mark', 'page', 'save'], category: 'Objects' },
  { emoji: '🏷️', keywords: ['label', 'tag', 'price', 'sale'], category: 'Objects' },
  { emoji: '✉️', keywords: ['envelope', 'letter', 'mail', 'email'], category: 'Objects' },
  { emoji: '📧', keywords: ['email', 'e-mail', 'mail', 'message'], category: 'Objects' },
  { emoji: '📨', keywords: ['envelope', 'incoming', 'mail', 'receive'], category: 'Objects' },
  { emoji: '📩', keywords: ['envelope', 'arrow', 'mail', 'outgoing'], category: 'Objects' },
  { emoji: '📤', keywords: ['outbox', 'sent', 'mail', 'tray'], category: 'Objects' },
  { emoji: '📥', keywords: ['inbox', 'receive', 'mail', 'tray'], category: 'Objects' },
  { emoji: '📪', keywords: ['mailbox', 'closed', 'mail', 'post'], category: 'Objects' },
  { emoji: '📫', keywords: ['mailbox', 'raised', 'mail', 'post'], category: 'Objects' },
  { emoji: '📬', keywords: ['mailbox', 'open', 'mail', 'post'], category: 'Objects' },
  { emoji: '📭', keywords: ['mailbox', 'lowered', 'mail', 'post'], category: 'Objects' },
  { emoji: '📮', keywords: ['postbox', 'mail', 'post', 'letter'], category: 'Objects' },
  { emoji: '🗳️', keywords: ['ballot', 'box', 'vote', 'election'], category: 'Objects' },
  { emoji: '🛒', keywords: ['cart', 'shopping', 'trolley', 'buy'], category: 'Objects' },
  { emoji: '⏰', keywords: ['alarm', 'clock', 'time', 'wake'], category: 'Objects' },
  { emoji: '⏱️', keywords: ['stopwatch', 'timer', 'time', 'race'], category: 'Objects' },
  { emoji: '⏲️', keywords: ['timer', 'clock', 'time', 'countdown'], category: 'Objects' },
  { emoji: '🕰️', keywords: ['clock', 'mantelpiece', 'time', 'antique'], category: 'Objects' },
  { emoji: '⌛', keywords: ['hourglass', 'done', 'time', 'sand'], category: 'Objects' },
  { emoji: '⏳', keywords: ['hourglass', 'flowing', 'time', 'sand'], category: 'Objects' },
  { emoji: '🔔', keywords: ['bell', 'notification', 'alert', 'ring'], category: 'Objects' },
  { emoji: '🔕', keywords: ['bell', 'mute', 'silent', 'notification'], category: 'Objects' },
  { emoji: '📣', keywords: ['megaphone', 'cheering', 'announcement'], category: 'Objects' },
  { emoji: '📢', keywords: ['loudspeaker', 'announcement', 'public'], category: 'Objects' },
  { emoji: '🔊', keywords: ['speaker', 'volume', 'loud', 'sound'], category: 'Objects' },
  { emoji: '🔉', keywords: ['speaker', 'volume', 'medium', 'sound'], category: 'Objects' },
  { emoji: '🔈', keywords: ['speaker', 'volume', 'low', 'sound'], category: 'Objects' },
  { emoji: '🔇', keywords: ['mute', 'speaker', 'silent', 'sound'], category: 'Objects' },
  { emoji: '🗑️', keywords: ['trash', 'bin', 'garbage', 'delete', 'waste'], category: 'Objects' },

  // Symbols & Shapes
  { emoji: '❤️', keywords: ['heart', 'red', 'love'], category: 'Symbols' },
  { emoji: '✅', keywords: ['check', 'yes', 'done', 'complete', 'success', 'green'], category: 'Symbols' },
  { emoji: '❌', keywords: ['cross', 'no', 'wrong', 'delete', 'red', 'x'], category: 'Symbols' },
  { emoji: '❎', keywords: ['cross', 'mark', 'no', 'square'], category: 'Symbols' },
  { emoji: '➕', keywords: ['plus', 'add', 'more', 'positive'], category: 'Symbols' },
  { emoji: '➖', keywords: ['minus', 'subtract', 'less', 'negative'], category: 'Symbols' },
  { emoji: '➗', keywords: ['divide', 'division', 'math'], category: 'Symbols' },
  { emoji: '✖️', keywords: ['multiply', 'x', 'cross', 'math'], category: 'Symbols' },
  { emoji: '💯', keywords: ['hundred', 'perfect', 'score', 'full'], category: 'Symbols' },
  { emoji: '💢', keywords: ['anger', 'angry', 'symbol', 'mad'], category: 'Symbols' },
  { emoji: '💥', keywords: ['boom', 'collision', 'explosion', 'crash'], category: 'Symbols' },
  { emoji: '💫', keywords: ['dizzy', 'star', 'circle', 'shooting'], category: 'Symbols' },
  { emoji: '💦', keywords: ['sweat', 'droplets', 'water', 'splash'], category: 'Symbols' },
  { emoji: '💨', keywords: ['dash', 'running', 'wind', 'fast'], category: 'Symbols' },
  { emoji: '🕳️', keywords: ['hole', 'black', 'empty', 'void'], category: 'Symbols' },
  { emoji: '💬', keywords: ['speech', 'bubble', 'talk', 'comment', 'chat'], category: 'Symbols' },
  { emoji: '👁️‍🗨️', keywords: ['eye', 'speech', 'witness', 'see'], category: 'Symbols' },
  { emoji: '🗨️', keywords: ['speech', 'bubble', 'left', 'talk'], category: 'Symbols' },
  { emoji: '🗯️', keywords: ['anger', 'bubble', 'right', 'mad'], category: 'Symbols' },
  { emoji: '💭', keywords: ['thought', 'bubble', 'think', 'idea'], category: 'Symbols' },
  { emoji: '💤', keywords: ['zzz', 'sleep', 'tired', 'snore'], category: 'Symbols' },
  { emoji: '🔷', keywords: ['diamond', 'blue', 'shape', 'rhombus'], category: 'Symbols' },
  { emoji: '🔶', keywords: ['diamond', 'orange', 'shape', 'rhombus'], category: 'Symbols' },
  { emoji: '🔹', keywords: ['diamond', 'blue', 'small', 'shape'], category: 'Symbols' },
  { emoji: '🔸', keywords: ['diamond', 'orange', 'small', 'shape'], category: 'Symbols' },
  { emoji: '🔺', keywords: ['triangle', 'red', 'up', 'shape'], category: 'Symbols' },
  { emoji: '🔻', keywords: ['triangle', 'red', 'down', 'shape'], category: 'Symbols' },
  { emoji: '◾', keywords: ['square', 'black', 'medium', 'shape'], category: 'Symbols' },
  { emoji: '◽', keywords: ['square', 'white', 'medium', 'shape'], category: 'Symbols' },
  { emoji: '▪️', keywords: ['square', 'black', 'small', 'shape'], category: 'Symbols' },
  { emoji: '▫️', keywords: ['square', 'white', 'small', 'shape'], category: 'Symbols' },
  { emoji: '⬛', keywords: ['square', 'black', 'large', 'shape'], category: 'Symbols' },
  { emoji: '⬜', keywords: ['square', 'white', 'large', 'shape'], category: 'Symbols' },
  { emoji: '🟥', keywords: ['square', 'red', 'shape', 'color'], category: 'Symbols' },
  { emoji: '🟧', keywords: ['square', 'orange', 'shape', 'color'], category: 'Symbols' },
  { emoji: '🟨', keywords: ['square', 'yellow', 'shape', 'color'], category: 'Symbols' },
  { emoji: '🟩', keywords: ['square', 'green', 'shape', 'color'], category: 'Symbols' },
  { emoji: '🟦', keywords: ['square', 'blue', 'shape', 'color'], category: 'Symbols' },
  { emoji: '🟪', keywords: ['square', 'purple', 'shape', 'color'], category: 'Symbols' },
  { emoji: '🟫', keywords: ['square', 'brown', 'shape', 'color'], category: 'Symbols' },
  { emoji: '⭕', keywords: ['circle', 'red', 'hollow', 'ring'], category: 'Symbols' },
  { emoji: '🔘', keywords: ['radio', 'button', 'circle', 'select'], category: 'Symbols' },
  { emoji: '🔴', keywords: ['circle', 'red', 'dot', 'round'], category: 'Symbols' },
  { emoji: '🟠', keywords: ['circle', 'orange', 'dot', 'round'], category: 'Symbols' },
  { emoji: '🟡', keywords: ['circle', 'yellow', 'dot', 'round'], category: 'Symbols' },
  { emoji: '🟢', keywords: ['circle', 'green', 'dot', 'round'], category: 'Symbols' },
  { emoji: '🔵', keywords: ['circle', 'blue', 'dot', 'round'], category: 'Symbols' },
  { emoji: '🟣', keywords: ['circle', 'purple', 'dot', 'round'], category: 'Symbols' },
  { emoji: '🟤', keywords: ['circle', 'brown', 'dot', 'round'], category: 'Symbols' },
  { emoji: '⚫', keywords: ['circle', 'black', 'dot', 'round'], category: 'Symbols' },
  { emoji: '⚪', keywords: ['circle', 'white', 'dot', 'round'], category: 'Symbols' },
  { emoji: '💠', keywords: ['diamond', 'dot', 'cute', 'flower', 'shape'], category: 'Symbols' },
  { emoji: '🔳', keywords: ['square', 'button', 'white', 'outline'], category: 'Symbols' },
  { emoji: '🔲', keywords: ['square', 'button', 'black', 'outline'], category: 'Symbols' },
  { emoji: '⭐', keywords: ['star', 'yellow', 'favorite', 'best'], category: 'Symbols' },
  { emoji: '🌟', keywords: ['star', 'glow', 'bright', 'shiny'], category: 'Symbols' },
  { emoji: '✨', keywords: ['sparkle', 'star', 'shine', 'magic', 'new'], category: 'Symbols' },
  { emoji: '⁉️', keywords: ['question', 'exclamation', 'interrobang', 'what'], category: 'Symbols' },
  { emoji: '❓', keywords: ['question', 'mark', 'red', 'what'], category: 'Symbols' },
  { emoji: '❔', keywords: ['question', 'mark', 'white', 'what'], category: 'Symbols' },
  { emoji: '❗', keywords: ['exclamation', 'mark', 'red', 'important'], category: 'Symbols' },
  { emoji: '❕', keywords: ['exclamation', 'mark', 'white', 'important'], category: 'Symbols' },
  { emoji: '‼️', keywords: ['exclamation', 'double', 'bang', 'important'], category: 'Symbols' },
  { emoji: '⚠️', keywords: ['warning', 'caution', 'alert', 'danger'], category: 'Symbols' },
  { emoji: '🚫', keywords: ['prohibited', 'no', 'forbidden', 'ban', 'stop'], category: 'Symbols' },
  { emoji: '🔞', keywords: ['eighteen', 'adult', 'nsfw', 'age'], category: 'Symbols' },
  { emoji: '📵', keywords: ['phone', 'no', 'prohibited', 'mobile'], category: 'Symbols' },
  { emoji: '🔃', keywords: ['arrows', 'clockwise', 'cycle', 'rotate'], category: 'Symbols' },
  { emoji: '🔄', keywords: ['arrows', 'counterclockwise', 'cycle', 'refresh', 'reload'], category: 'Symbols' },
  { emoji: '🔙', keywords: ['back', 'arrow', 'return', 'previous'], category: 'Symbols' },
  { emoji: '🔚', keywords: ['end', 'arrow', 'finish', 'last'], category: 'Symbols' },
  { emoji: '🔛', keywords: ['on', 'arrow', 'mark', 'top'], category: 'Symbols' },
  { emoji: '🔜', keywords: ['soon', 'arrow', 'coming', 'next'], category: 'Symbols' },
  { emoji: '🔝', keywords: ['top', 'arrow', 'up', 'first'], category: 'Symbols' },
  { emoji: '⬆️', keywords: ['arrow', 'up', 'north', 'direction'], category: 'Symbols' },
  { emoji: '⬇️', keywords: ['arrow', 'down', 'south', 'direction'], category: 'Symbols' },
  { emoji: '⬅️', keywords: ['arrow', 'left', 'west', 'direction'], category: 'Symbols' },
  { emoji: '➡️', keywords: ['arrow', 'right', 'east', 'direction'], category: 'Symbols' },
  { emoji: '↗️', keywords: ['arrow', 'northeast', 'up', 'right'], category: 'Symbols' },
  { emoji: '↘️', keywords: ['arrow', 'southeast', 'down', 'right'], category: 'Symbols' },
  { emoji: '↙️', keywords: ['arrow', 'southwest', 'down', 'left'], category: 'Symbols' },
  { emoji: '↖️', keywords: ['arrow', 'northwest', 'up', 'left'], category: 'Symbols' },
  { emoji: '↕️', keywords: ['arrow', 'up', 'down', 'vertical'], category: 'Symbols' },
  { emoji: '↔️', keywords: ['arrow', 'left', 'right', 'horizontal'], category: 'Symbols' },
  { emoji: '🔀', keywords: ['shuffle', 'random', 'crossed', 'arrows'], category: 'Symbols' },
  { emoji: '🔁', keywords: ['repeat', 'loop', 'arrows', 'cycle'], category: 'Symbols' },
  { emoji: '🔂', keywords: ['repeat', 'one', 'single', 'loop'], category: 'Symbols' },
  { emoji: '▶️', keywords: ['play', 'arrow', 'forward', 'start'], category: 'Symbols' },
  { emoji: '⏩', keywords: ['fast', 'forward', 'skip', 'double'], category: 'Symbols' },
  { emoji: '⏭️', keywords: ['next', 'track', 'skip', 'forward'], category: 'Symbols' },
  { emoji: '⏯️', keywords: ['play', 'pause', 'toggle'], category: 'Symbols' },
  { emoji: '◀️', keywords: ['reverse', 'back', 'left', 'arrow'], category: 'Symbols' },
  { emoji: '⏪', keywords: ['rewind', 'back', 'fast', 'double'], category: 'Symbols' },
  { emoji: '⏮️', keywords: ['previous', 'track', 'skip', 'back'], category: 'Symbols' },
  { emoji: '⏸️', keywords: ['pause', 'stop', 'hold', 'double'], category: 'Symbols' },
  { emoji: '⏹️', keywords: ['stop', 'square', 'end'], category: 'Symbols' },
  { emoji: '⏺️', keywords: ['record', 'circle', 'red', 'dot'], category: 'Symbols' },
  { emoji: '🎦', keywords: ['cinema', 'movie', 'film', 'camera'], category: 'Symbols' },
  { emoji: '🔅', keywords: ['dim', 'low', 'brightness', 'sun'], category: 'Symbols' },
  { emoji: '🔆', keywords: ['bright', 'high', 'brightness', 'sun'], category: 'Symbols' },
  { emoji: '📶', keywords: ['signal', 'strength', 'antenna', 'bars'], category: 'Symbols' },
  { emoji: '📳', keywords: ['vibration', 'mode', 'phone', 'silent'], category: 'Symbols' },
  { emoji: '📴', keywords: ['off', 'phone', 'mobile', 'silent'], category: 'Symbols' },
  { emoji: '♀️', keywords: ['female', 'woman', 'venus', 'gender'], category: 'Symbols' },
  { emoji: '♂️', keywords: ['male', 'man', 'mars', 'gender'], category: 'Symbols' },
  { emoji: '⚧️', keywords: ['transgender', 'symbol', 'gender'], category: 'Symbols' },
  { emoji: '♻️', keywords: ['recycle', 'environment', 'green', 'eco'], category: 'Symbols' },
  { emoji: '⚜️', keywords: ['fleur', 'de', 'lis', 'scout', 'french'], category: 'Symbols' },
  { emoji: '🔱', keywords: ['trident', 'emblem', 'poseidon', 'anchor'], category: 'Symbols' },
  { emoji: '📛', keywords: ['name', 'badge', 'tag', 'id'], category: 'Symbols' },
  { emoji: '🔰', keywords: ['beginner', 'japanese', 'symbol', 'new'], category: 'Symbols' },
  { emoji: '⭕', keywords: ['circle', 'o', 'round', 'ring'], category: 'Symbols' },
  { emoji: '✅', keywords: ['check', 'mark', 'button', 'yes'], category: 'Symbols' },
  { emoji: '☑️', keywords: ['check', 'box', 'vote', 'ballot'], category: 'Symbols' },
  { emoji: '✔️', keywords: ['check', 'mark', 'heavy', 'done'], category: 'Symbols' },
  { emoji: '©️', keywords: ['copyright', 'c', 'ip', 'legal'], category: 'Symbols' },
  { emoji: '®️', keywords: ['registered', 'r', 'trademark', 'legal'], category: 'Symbols' },
  { emoji: '™️', keywords: ['trademark', 'tm', 'brand', 'legal'], category: 'Symbols' },
  { emoji: '#️⃣', keywords: ['hashtag', 'number', 'pound', 'key'], category: 'Symbols' },
  { emoji: '*️⃣', keywords: ['asterisk', 'star', 'key'], category: 'Symbols' },
  { emoji: '0️⃣', keywords: ['zero', 'number', '0', 'keycap'], category: 'Symbols' },
  { emoji: '1️⃣', keywords: ['one', 'number', '1', 'keycap'], category: 'Symbols' },
  { emoji: '2️⃣', keywords: ['two', 'number', '2', 'keycap'], category: 'Symbols' },
  { emoji: '3️⃣', keywords: ['three', 'number', '3', 'keycap'], category: 'Symbols' },
  { emoji: '4️⃣', keywords: ['four', 'number', '4', 'keycap'], category: 'Symbols' },
  { emoji: '5️⃣', keywords: ['five', 'number', '5', 'keycap'], category: 'Symbols' },
  { emoji: '6️⃣', keywords: ['six', 'number', '6', 'keycap'], category: 'Symbols' },
  { emoji: '7️⃣', keywords: ['seven', 'number', '7', 'keycap'], category: 'Symbols' },
  { emoji: '8️⃣', keywords: ['eight', 'number', '8', 'keycap'], category: 'Symbols' },
  { emoji: '9️⃣', keywords: ['nine', 'number', '9', 'keycap'], category: 'Symbols' },
  { emoji: '🔟', keywords: ['ten', 'number', '10', 'keycap'], category: 'Symbols' },
  { emoji: '🅰️', keywords: ['a', 'letter', 'blood', 'type'], category: 'Symbols' },
  { emoji: '🆎', keywords: ['ab', 'blood', 'type', 'letter'], category: 'Symbols' },
  { emoji: '🅱️', keywords: ['b', 'letter', 'blood', 'type'], category: 'Symbols' },
  { emoji: '🆑', keywords: ['cl', 'clear', 'button'], category: 'Symbols' },
  { emoji: '🆒', keywords: ['cool', 'word', 'button'], category: 'Symbols' },
  { emoji: '🆓', keywords: ['free', 'word', 'button'], category: 'Symbols' },
  { emoji: 'ℹ️', keywords: ['info', 'information', 'help'], category: 'Symbols' },
  { emoji: '🆔', keywords: ['id', 'identity', 'button'], category: 'Symbols' },
  { emoji: 'Ⓜ️', keywords: ['m', 'circle', 'metro', 'letter'], category: 'Symbols' },
  { emoji: '🆕', keywords: ['new', 'word', 'button'], category: 'Symbols' },
  { emoji: '🆖', keywords: ['ng', 'no', 'good', 'button'], category: 'Symbols' },
  { emoji: '🅾️', keywords: ['o', 'letter', 'blood', 'type'], category: 'Symbols' },
  { emoji: '🆗', keywords: ['ok', 'word', 'button', 'yes'], category: 'Symbols' },
  { emoji: '🅿️', keywords: ['p', 'parking', 'letter', 'button'], category: 'Symbols' },
  { emoji: '🆘', keywords: ['sos', 'help', 'emergency', 'button'], category: 'Symbols' },
  { emoji: '🆙', keywords: ['up', 'word', 'button', 'exclamation'], category: 'Symbols' },
  { emoji: '🆚', keywords: ['vs', 'versus', 'against', 'button'], category: 'Symbols' },

  // Flags (common ones)
  { emoji: '🏁', keywords: ['checkered', 'flag', 'race', 'finish'], category: 'Flags' },
  { emoji: '🚩', keywords: ['flag', 'triangular', 'red', 'post'], category: 'Flags' },
  { emoji: '🎌', keywords: ['flags', 'crossed', 'japanese', 'celebration'], category: 'Flags' },
  { emoji: '🏴', keywords: ['flag', 'black', 'waving'], category: 'Flags' },
  { emoji: '🏳️', keywords: ['flag', 'white', 'surrender', 'peace'], category: 'Flags' },
  { emoji: '🏳️‍🌈', keywords: ['rainbow', 'flag', 'pride', 'lgbtq', 'gay'], category: 'Flags' },
  { emoji: '🏳️‍⚧️', keywords: ['transgender', 'flag', 'pride', 'trans'], category: 'Flags' },
  { emoji: '🏴‍☠️', keywords: ['pirate', 'flag', 'jolly', 'roger', 'skull'], category: 'Flags' },
  { emoji: '🇺🇸', keywords: ['usa', 'america', 'flag', 'united', 'states'], category: 'Flags' },
  { emoji: '🇬🇧', keywords: ['uk', 'britain', 'england', 'flag', 'united', 'kingdom'], category: 'Flags' },
  { emoji: '🇨🇦', keywords: ['canada', 'flag', 'maple'], category: 'Flags' },
  { emoji: '🇦🇺', keywords: ['australia', 'flag', 'aussie'], category: 'Flags' },
  { emoji: '🇯🇵', keywords: ['japan', 'flag', 'japanese'], category: 'Flags' },
  { emoji: '🇰🇷', keywords: ['korea', 'south', 'flag', 'korean'], category: 'Flags' },
  { emoji: '🇨🇳', keywords: ['china', 'flag', 'chinese'], category: 'Flags' },
  { emoji: '🇮🇳', keywords: ['india', 'flag', 'indian'], category: 'Flags' },
  { emoji: '🇩🇪', keywords: ['germany', 'flag', 'german'], category: 'Flags' },
  { emoji: '🇫🇷', keywords: ['france', 'flag', 'french'], category: 'Flags' },
  { emoji: '🇮🇹', keywords: ['italy', 'flag', 'italian'], category: 'Flags' },
  { emoji: '🇪🇸', keywords: ['spain', 'flag', 'spanish'], category: 'Flags' },
  { emoji: '🇧🇷', keywords: ['brazil', 'flag', 'brazilian'], category: 'Flags' },
  { emoji: '🇲🇽', keywords: ['mexico', 'flag', 'mexican'], category: 'Flags' },
  { emoji: '🇷🇺', keywords: ['russia', 'flag', 'russian'], category: 'Flags' },
  { emoji: '🇳🇱', keywords: ['netherlands', 'flag', 'dutch', 'holland'], category: 'Flags' },
  { emoji: '🇸🇪', keywords: ['sweden', 'flag', 'swedish'], category: 'Flags' },
  { emoji: '🇳🇴', keywords: ['norway', 'flag', 'norwegian'], category: 'Flags' },
  { emoji: '🇵🇱', keywords: ['poland', 'flag', 'polish'], category: 'Flags' },
  { emoji: '🇺🇦', keywords: ['ukraine', 'flag', 'ukrainian'], category: 'Flags' },
];

// Group emojis by category
const EMOJI_BY_CATEGORY = EMOJI_DATA.reduce((acc, item) => {
  if (!acc[item.category]) acc[item.category] = [];
  acc[item.category].push(item);
  return acc;
}, {} as Record<string, typeof EMOJI_DATA>);

// Category order
const CATEGORY_ORDER = [
  'Smileys', 'People', 'Gestures', 'Hearts', 'Animals', 'Nature', 'Weather',
  'Food', 'Tools', 'Tech', 'Transport', 'Objects', 'Symbols', 'Flags',
];

interface EmojiPickerProps {
  value: string;
  onChange: (emoji: string) => void;
}

export function EmojiPicker({ value, onChange }: EmojiPickerProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState('');
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const filteredResults = useMemo(() => {
    const query = search.trim().toLowerCase();
    if (!query) {
      return CATEGORY_ORDER.map(category => ({
        category,
        emojis: EMOJI_BY_CATEGORY[category] || [],
      })).filter(group => group.emojis.length > 0);
    }
    const matches = EMOJI_DATA.filter(item =>
      item.keywords.some(keyword => keyword.includes(query)) || item.emoji === query
    );
    return matches.length ? [{ category: 'Results', emojis: matches }] : [];
  }, [search]);

  const handleSelect = (emoji: string) => {
    onChange(emoji);
    setIsOpen(false);
    setSearch('');
  };

  return (
    <div ref={containerRef} className="emoji-picker-container">
      <div className="emoji-picker-input-wrapper">
        <input
          type="text"
          className="form-input emoji-picker-input"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder="🚀"
          onClick={() => setIsOpen(true)}
          style={{ textAlign: 'center', fontSize: '18px', paddingRight: '32px' }}
        />
        <button
          type="button"
          className="emoji-picker-toggle"
          onClick={() => setIsOpen(!isOpen)}
          title="Browse emojis"
        >
          ▼
        </button>
      </div>
      {isOpen && (
        <div className="emoji-picker-dropdown">
          <div className="emoji-picker-search">
            <input
              type="text"
              className="form-input"
              placeholder="Search emojis..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              autoFocus
            />
          </div>
          <div className="emoji-picker-grid-container">
            {filteredResults.length === 0 ? (
              <div className="emoji-picker-empty">No emojis found</div>
            ) : (
              filteredResults.map(({ category, emojis }) => (
                <div key={category} className="emoji-picker-category">
                  <div className="emoji-picker-category-label">{category}</div>
                  <div className="emoji-picker-grid">
                    {emojis.map((item, idx) => (
                      <button
                        key={`${item.emoji}-${idx}`}
                        type="button"
                        className={`emoji-picker-item ${value === item.emoji ? 'selected' : ''}`}
                        onClick={() => handleSelect(item.emoji)}
                        title={item.keywords.slice(0, 3).join(', ')}
                      >
                        {item.emoji}
                      </button>
                    ))}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
}
