import React from 'react';
import {
  // Agent classes
  MagnifyingGlass,
  Hammer,
  Bug,
  Triangle,
  Sword,
  Heart,
  Crown,
  Robot,
  // Status
  CircleNotch,
  Moon,
  CheckCircle,
  XCircle,
  Warning,
  WarningCircle,
  Info,
  Question,
  Spinner,
  Circle,
  Clock,
  Hourglass,
  // Actions
  Trash,
  PencilSimple,
  Copy,
  ClipboardText,
  FloppyDisk,
  ArrowsClockwise,
  Play,
  Stop,
  Pause,
  Rocket,
  Recycle,
  Stethoscope,
  Link,
  Broom,
  ArrowUUpLeft,
  PushPin,
  Plus,
  Minus,
  ArrowSquareOut,
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  ArrowsLeftRight,
  ArrowsDownUp,
  DownloadSimple,
  UploadSimple,
  HandPointing,
  // UI controls
  Check,
  X,
  CaretDown,
  CaretRight,
  CaretUp,
  CaretLeft,
  CaretDoubleDown,
  CaretDoubleUp,
  ArrowBendDownRight,
  ArrowsOut,
  ArrowsIn,
  DotsThreeVertical,
  List,
  Star,
  Square,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquaresFour,
  Hexagon,
  // Domain
  Database,
  Folder,
  FolderOpen,
  Folders,
  TerminalWindow,
  DesktopTower,
  Monitor,
  Keyboard,
  Eye,
  EyeClosed,
  File as FileIcon,
  FileText,
  FileCode,
  FilePlus,
  FileZip,
  Paperclip,
  GitBranch,
  GitCommit,
  GitMerge,
  ChartBar,
  ChartLine,
  Lightning,
  Package,
  Archive,
  Wrench,
  Bell,
  ListChecks,
  ListBullets,
  ChatCircle,
  Gear,
  PaperPlaneTilt,
  Palette,
  TreeView,
  SpeakerHigh,
  SpeakerSimpleSlash,
  Lightbulb,
  Lock,
  LockOpen,
  Target,
  Megaphone,
  Dna,
  Flask,
  Sparkle,
  MagicWand,
  Skull,
  MapTrifold,
  PathIcon,
  Envelope,
  EnvelopeSimple,
  PlayCircle,
  Scroll,
  Eraser,
  Brain,
  Microphone,
  Record,
  Globe,
  GlobeHemisphereWest,
  Atom,
  Key,
  Shield,
  Waves,
  Sun,
  CloudSun,
  CloudMoon,
  Flame,
  Snowflake,
  Leaf,
  Plant,
  CoffeeIcon,
  MusicNote,
  FilmStrip,
  DeviceMobile,
  Disc,
  HardDrives,
  FrameCorners,
  Plug,
  PlugsConnected,
  WifiHigh,
  UsersThree,
  UserCircle,
  PaintBucket,
  Factory,
  BuildingOffice,
  Buildings,
  Door,
  Briefcase,
  Calendar,
  MusicNotes,
  ThumbsUp,
  ThumbsDown,
  PersonSimpleWalk,
  PersonSimpleRun,
  HouseSimple,
  ArrowClockwise,
  StarFour,
  Cube,
  Signature,
  ArrowUpRight,
  ArrowDownRight,
  ArrowFatUp,
  ArrowFatDown,
  ArrowFatLeft,
  ArrowFatRight,
  LineVertical,
  type Icon as PhosphorIcon,
  type IconWeight,
} from '@phosphor-icons/react';

// Semantic name → Phosphor icon mapping.
// Keep names aligned with how the icon is *used* in the UI, not the Phosphor identifier.
export const ICON_MAP = {
  // Agent classes
  'class-scout': MagnifyingGlass,
  'class-builder': Hammer,
  'class-debugger': Bug,
  'class-architect': Triangle,
  'class-warrior': Sword,
  'class-support': Heart,
  'class-boss': Crown,
  'class-default': Robot,

  // Status
  'status-running': CircleNotch,
  'status-stopped': Stop,
  'status-error': WarningCircle,
  'status-unknown': Question,
  'status-starting': Spinner,
  'status-stopping': Pause,
  'status-working': CircleNotch,
  'status-idle': Moon,
  'status-waiting-input': Clock,
  'status-waiting-permission': Lock,
  'status-success': CheckCircle,
  'status-failure': XCircle,
  'status-pending': Circle,
  'warn': Warning,
  'info': Info,
  'question': Question,
  'check': Check,
  'cross': X,
  'success': CheckCircle,
  'failure': XCircle,

  // Actions
  'trash': Trash,
  'edit': PencilSimple,
  'copy': Copy,
  'clipboard': ClipboardText,
  'save': FloppyDisk,
  'refresh': ArrowsClockwise,
  'play': Play,
  'stop': Stop,
  'pause': Pause,
  'launch': Rocket,
  'restart': Recycle,
  'health': Stethoscope,
  'link': Link,
  'clear': Broom,
  'revert': ArrowUUpLeft,
  'pin': PushPin,
  'plus': Plus,
  'minus': Minus,
  'open-external': ArrowSquareOut,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrows-horizontal': ArrowsLeftRight,
  'arrows-vertical': ArrowsDownUp,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  'arrow-fat-up': ArrowFatUp,
  'arrow-fat-down': ArrowFatDown,
  'arrow-fat-left': ArrowFatLeft,
  'arrow-fat-right': ArrowFatRight,
  'download': DownloadSimple,
  'upload': UploadSimple,
  'close': X,
  'delete': Trash,
  'erase': Eraser,
  'hand-point': HandPointing,
  'record': Record,
  'caret-left': CaretLeft,
  'caret-double-down': CaretDoubleDown,
  'caret-double-up': CaretDoubleUp,
  'hourglass': Hourglass,

  // UI controls
  'caret-down': CaretDown,
  'caret-right': CaretRight,
  'caret-up': CaretUp,
  'subitem': ArrowBendDownRight,
  'fullscreen': ArrowsOut,
  'exit-fullscreen': ArrowsIn,
  'search': MagnifyingGlass,
  'more': DotsThreeVertical,
  'list': List,
  'list-checks': ListChecks,
  'list-bullets': ListBullets,

  // Domain
  'database': Database,
  'folder': Folder,
  'folder-open': FolderOpen,
  'terminal': TerminalWindow,
  'eye': Eye,
  'file': FileIcon,
  'file-text': FileText,
  'file-code': FileCode,
  'file-add': FilePlus,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-diff': GitCommit,
  'dashboard': ChartBar,
  'bolt': Lightning,
  'package': Package,
  'wrench': Wrench,
  'bell': Bell,
  'chat': ChatCircle,
  'gear': Gear,
  'send': PaperPlaneTilt,
  'palette': Palette,
  'tree': TreeView,
  'speaker-on': SpeakerHigh,
  'speaker-off': SpeakerSimpleSlash,
  'idea': Lightbulb,
  'lock': Lock,
  'unlock': LockOpen,
  'target': Target,
  'announce': Megaphone,
  'dna': Dna,
  'flask': Flask,
  'sparkle': Sparkle,
  'skull': Skull,
  'map': MapTrifold,
  'path': PathIcon,
  'envelope': Envelope,
  'play-circle': PlayCircle,
  'scroll': Scroll,

  // Tools / semantic aliases
  'tool': Wrench,
  'task': ListBullets,
  'hammer': Hammer,
  'bug': Bug,
  'crown': Crown,
  'robot': Robot,
  'heart': Heart,

  // Extended domain
  'square': Square,
  'split-horizontal': SquareSplitHorizontal,
  'split-vertical': SquareSplitVertical,
  'grid': SquaresFour,
  'hexagon': Hexagon,
  'star': Star,
  'star-four': StarFour,
  'eye-closed': EyeClosed,
  'folders': Folders,
  'desktop': DesktopTower,
  'monitor': Monitor,
  'keyboard': Keyboard,
  'file-zip': FileZip,
  'paperclip': Paperclip,
  'git-merge': GitMerge,
  'chart-line': ChartLine,
  'archive': Archive,
  'envelope-simple': EnvelopeSimple,
  'brain': Brain,
  'microphone': Microphone,
  'globe': Globe,
  'globe-hemisphere': GlobeHemisphereWest,
  'atom': Atom,
  'key': Key,
  'shield': Shield,
  'waves': Waves,
  'sun': Sun,
  'cloud-sun': CloudSun,
  'cloud-moon': CloudMoon,
  'moon': Moon,
  'flame': Flame,
  'snowflake': Snowflake,
  'leaf': Leaf,
  'plant': Plant,
  'coffee': CoffeeIcon,
  'music-note': MusicNote,
  'music-notes': MusicNotes,
  'film': FilmStrip,
  'mobile': DeviceMobile,
  'disc': Disc,
  'hard-drives': HardDrives,
  'frame': FrameCorners,
  'plug': Plug,
  'plugs-connected': PlugsConnected,
  'wifi': WifiHigh,
  'users': UsersThree,
  'user-circle': UserCircle,
  'paint-bucket': PaintBucket,
  'factory': Factory,
  'building-office': BuildingOffice,
  'buildings': Buildings,
  'door': Door,
  'briefcase': Briefcase,
  'calendar': Calendar,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'walk': PersonSimpleWalk,
  'run': PersonSimpleRun,
  'house': HouseSimple,
  'arrow-clockwise': ArrowClockwise,
  'cube': Cube,
  'signature': Signature,
  'line-vertical': LineVertical,
  'magic-wand': MagicWand,
  'warning-circle': WarningCircle,
} as const satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICON_MAP;

export interface IconProps {
  name: IconName;
  size?: number | string;
  weight?: IconWeight;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  title?: string;
  'aria-hidden'?: boolean;
}

/**
 * Centralized icon component backed by Phosphor Icons.
 * Use semantic names (e.g. "trash", "class-scout") so the visual library can be swapped
 * in one place.
 */
export const Icon = React.memo(function Icon({
  name,
  size = 16,
  weight = 'regular',
  color,
  className,
  style,
  title,
  'aria-hidden': ariaHidden,
}: IconProps) {
  const Component = ICON_MAP[name];
  if (!Component) {
    if (import.meta.env?.DEV) {
      console.warn(`[Icon] Unknown icon name "${name}"`);
    }
    return null;
  }
  return (
    <Component
      size={size}
      weight={weight}
      color={color}
      className={className}
      style={style}
      aria-hidden={ariaHidden}
    >
      {title ? <title>{title}</title> : null}
    </Component>
  );
});

export default Icon;
